name: Deploy
on:
  push:
    tags:
      - "*"

jobs:
  publish-doc:
    runs-on: ubuntu-20.04
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install Dependencies
        run: |
          npm install

      - name: Build document
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./lib
          output_dir: ./docs
          config_file: .jsdoc.json
          template: minami
          front_page: README.md

      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs/

      - id: deployment
        uses: actions/deploy-pages@v1
